Wemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("wemo_app/", include("wemo_app.urls")),
    path('admin/', admin.site.urls),
]

wemo_app/urls.py
from django.urls import path

from . import views

app_name = "wemo_app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("memo_list/", views.MemoListView.as_view(), name="memo_list"),
    path("memo_list/<int:pk>/", views.MemoView.as_view(),
         name="memo_view"),
    path("memo_create/", views.MemoCreateFormView.as_view(),
         name="memo_create"),
    path("memo_create/add/", views.MemoCreateView.as_view(),
         name="memo_add"),
    path("credit", views.CreditView.as_view(), name="credit"),
    path("memo_list/<int:pk>/delete", views.MemoDeleteView.as_view(),
         name="memo_delete"),
    path("memo_list/<int:pk>/update", views.MemoUpdateView.as_view(),
         name="memo_update"),
    path("help/", views.HelpView.as_view(), name="help")
]

wemo_app/models.py
from django.db import models


class Memo(models.Model):
    memo_title = models.CharField(max_length=77)
    memo_text = models.TextField()

    def __str__(self):
        return self.memo_title

wemo_app/forms.py
from django import forms

from .models import Memo


class MemoCreateForm(forms.ModelForm):

    class Meta:
        model = Memo
        fields = ("memo_title", "memo_text")
        widgets = {
            "memo_title": forms.TextInput(
                attrs={"class": "w3-input w3-border"}),
            "memo_text": forms.Textarea(
                attrs={"class": "w3-input w3-border"}),
        }


class MemoUpdateForm(forms.ModelForm):

    class Meta:
        model = Memo
        fields = ("memo_title", "memo_text")
        widgets = {
            "memo_title": forms.TextInput(
                attrs={"class": "w3-input w3-border"}),
            "memo_text": forms.Textarea(
                attrs={"class": "w3-input w3-border"}),
        }

wemo_app/views.py
from django.views import generic
from django.urls import reverse_lazy

from .forms import MemoCreateForm, MemoUpdateForm
from .models import Memo


class IndexView(generic.TemplateView):
    template_name = "wemo_app/index.html"


class MemoListView(generic.ListView):
    template_name = "wemo_app/memo_list.html"

    def get_queryset(self):
        return Memo.objects.all()


class MemoView(generic.DetailView):
    model = Memo
    template_name = "wemo_app/memo_view.html"


class MemoCreateFormView(generic.edit.FormView):
    template_name = "wemo_app/memo_create.html"
    form_class = MemoCreateForm


class MemoCreateView(generic.edit.CreateView):
    model = Memo
    fields = ("memo_title", "memo_text")
    success_url = reverse_lazy("wemo_app:memo_list")


class MemoUpdateView(generic.edit.UpdateView):
    model = Memo
    form_class = MemoUpdateForm
    template_name = "wemo_app/memo_update.html"
    success_url = reverse_lazy("wemo_app:memo_list")


class CreditView(generic.TemplateView):
    template_name = "wemo_app/credit.html"


class MemoDeleteView(generic.edit.DeleteView):
    model = Memo
    success_url = reverse_lazy("wemo_app:memo_list")


class HelpView(generic.TemplateView):
    template_name = "wemo_app/help.html"

wemo_app/templates/wemo_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Wemo | {% block subtitle %}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'wemo_app/w3.css' %}">
    <link rel="stylesheet" href="{% static 'wemo_app/w3-theme.css' %}">
</head>
<body {% block body_attr %}{% endblock %}>
    <div class="w3-container {% block content_display %}{% endblock %} w3-mobile w3-center w3-text-theme w3-theme-light w3-round w3-card">
        {% block content %}
        {% endblock %}
        <nav>
            <div class="w3-bar w3-border-top">
                <div class="w3-bar-item w3-button w3-mobile">
                    <small>&copy;2018 junichi2</small>
                </div>
                <a href="{% url 'wemo_app:index' %}" class="w3-bar-item w3-button w3-mobile">
                    Wemo
                </a>
                <a href="{% url 'wemo_app:credit' %}" class="w3-bar-item  w3-button w3-mobile">
                    利用規約・ライセンス
                </a>
                <a href="{% url 'wemo_app:help' %}" class="w3-bar-item w3-button w3-mobile">
                    ヘルプ
                </a>
            </div>
        </nav>
    </div>
</body>
</html>

wemo_app/templates/wemo_app/credit.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme-l4 w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-top{% endblock %}

{% block content %}
<h1>利用規約</h1>
<p class="w3-padding w3-border w3-round w3-text-indigo">
    Wemoはjunichi2(以下「運営」といいます)が開発運営するWebサービスです。<br>
    Wemoをご利用いただく前に、本規約への皆様の同意が必要になります。<br>
    恐れ入りますが、下記をお読みください。
</p>
<div class="w3-padding w3-border w3-round w3-margin-bottom">
    <div class="w3-border-bottom">
        <h2>第1条 (適用)</h2>
        <p class="w3-text-indigo">本規約はユーザーと運営との間の本サービスの利用に関わる一切の関係に適用されます。</p>
    </div>
    <div class="w3-border-bottom">
        <h2>第2条 (定義)</h2>
        <p class="w3-text-indigo">本サービスのユーザーとは、本サービスを利用するユーザー全体の総称です。</p>
    </div>
    <div class="w3-border-bottom">
        <h2>第3条 (禁止事項)</h2>
        <p class="w3-text-indigo">ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>
        <ol>
            <li>法令または公序良俗に違反する行為</li>
            <li>犯罪行為に関連する行為</li>
            <li>サービスのサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
            <li>サービスの運営を妨害するおそれのある行為</li>
            <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
            <li>他のユーザーに成りすます行為</li>
            <li>その他運営が不適切と判断する行為</li>
        </ol>
    </div>
    <div class="w3-border-bottom">
        <h2>第4条 (本サービスの提供の停止等)</h2>
        <p class="w3-text-indigo">
            運営は、以下のいずれかの事由があると判断した場合、<br>
            本サービスの全部または一部の提供を停止または中断することができるものとします。
            <ul>
                <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
                <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
                <li>コンピュータまたは通信回線等が事故により停止した場合</li>
                <li>その他、本サービスの提供が困難と判断した場合</li>
            </ul>
        </p>
    </div>
    <div class="w3-border-bottom">
        <h2>第5条 (ユーザーの責任)</h2>
        <p>
            <ul class="w3-ul">
                <li>
                    <p>
                        本サービスをユーザーが利用する場合、インターネットにアクセスする必要がありますが、<br>
                        そのためのあらゆる機器、ソフトウェア、通信手段はユーザーご自身が<br>
                        各自の責任と費用において適切に準備、設置、操作していただく必要があります。
                    </p>
                    <p>
                        当社はユーザーのアクセス環境について一切関与せず、これらの準備、操作に関する責任を負いません。
                    </p>
                </li>
                <li>
                    <p>
                        本サービス上においてユーザーが開示した、<br>
                        テキストに付随する情報や個人情報などを含む<br>
                        全ての情報に関する責任は、ユーザー各自にあります。
                    </p>
                    <p>
                        従って、運営はユーザーが本サービスにおいて開示した情報の内容について、一切の責任を負いません。
                    </p>
                </li>
            </ul>
        </p>
    </div>
    <div class="w3-border-bottom">
        <h2>第6条 (準拠法)</h2>
        <p class="w3-text-indigo">
            本規約は、日本法に準拠して解釈されるものとします。
        </p>
    </div>
    <p>(2018年1月30日 制定)</p>
</div>
{% endblock %}

wemo_app/templates/wemo_app/help.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme-l4 w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-top{% endblock %}

{% block content %}
<div class="w3-padding w3-border w3-round w3-margin-bottom">
    <h1>ヘルプ</h1>
    <div class="w3-border w3-margin w3-round">
        <h2>目次</h2>
        <ul class="w3-ul">
            <li>
                <a href="#create">メモの作り方</a>
            </li>
            <li>
                <a href="#delete">メモを削除する</a>
            </li>
            <li>
                <a href="#edit">メモを書き直す</a>
            </li>
        </ul>
    </div>
    <div id="create">
        <h2>メモの作り方</h2>
        <p></p>
    </div>
    <div id="delete">
        <h2>メモを削除する</h2>
        <p></p>
    </div>
    <div id="edit">
        <h2>メモを書き直す</h2>
        <p></p>
    </div>
</div>
{% endblock %}

wemo_app/templates/wemo_app/index.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモをカンタンに。お手軽に。{% endblock %}

{% block body_attr %}class="w3-theme w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-middle{% endblock %}

{% block content %}
<div class="w3-border-bottom w3-margin">
    <h1>Wemo</h1>
</div>
<img src="{% static 'wemo_app/images/Paper-notes.svg' %}" width="100vm" class="w3-animate-zoom">
<h2>メモをカンタンに。お手軽に。</h2>
<p>WemoはWeb上でメモを作成・管理できるオンラインメモアプリです。</p>
<a href="{% url 'wemo_app:memo_list' %}" class="w3-button w3-round-large w3-ripple w3-margin w3-border">
    はじめる
</a>
{% endblock %}

wemo_app/templates/wemo_app/memo_create.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme-l4 w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-top{% endblock %}

{% block content %}
<div class="w3-border-bottom w3-margin">
    <h1>メモを新しくつくる</h1>
</div>
<form class="w3-container w3-margin-bottom w3-margin-top" action="{% url 'wemo_app:memo_add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="OK" class="w3-input w3-button w3-border w3-round w3-ripple">
</form>
<a href="{% url 'wemo_app:memo_list' %}" class="w3-button w3-border w3-round-large w3-margin-bottom w3-margin-top">
    <i class="material-icons w3-large">home メモ一覧に戻る</i>
</a>
{% endblock %}

wemo_app/templates/wemo_app/memo_list.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme-l4 w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-top{% endblock %}

{% block content %}
<div class="w3-border-bottom w3-margin-bottom">
    <h1>メモ一覧</h1>
</div>
<div class="w3-border-bottom w3-margin-bottom">
    <ul class="w3-ul">
    {% for memo in memo_list %}
        <a href="{% url 'wemo_app:memo_view' memo.id %}" class="w3-mobile">
            <li class="w3-border w3-round w3-margin-bottom w3-hover-border-theme">
                <h2>{{ memo.memo_title|slice:":30" }}</h2>
                <span class="w3-small">{{ memo.memo_text|slice:":28" }}…</span>
            </li>
        </a>
    {% endfor %}
    </ul>
</div>
<a href="{% url 'wemo_app:memo_create' %}" class="w3-button w3-border w3-round-large w3-margin-bottom w3-ripple">
    <i class="material-icons w3-large">create メモをつくる</i>
</a>
{% endblock %}

wemo_app/templates/wemo_app/memo_update.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme-l4 w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-top{% endblock %}

{% block content %}
<div class="w3-border-bottom w3-margin">
    <h1>メモを書き直す</h1>
</div>
<form action="{% url 'wemo_app:memo_update' memo.id %}" class="w3-container w3-margin-bottom w3-margin-top" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="OK" class="w3-input w3-button w3-border w3-round w3-ripple">
</form>

<a href="{% url 'wemo_app:memo_list' %}" class="w3-button w3-border w3-round-large w3-margin-bottom w3-margin-top">
    <i class="material-icons w3-large">home メモ一覧に戻る</i>
</a>
{% endblock %}

wemo_app/templates/wemo_app/memo_view.html
{% extends "wemo_app/base.html" %}

{% load static %}

{% block subtitle %}メモ一覧{% endblock %}

{% block body_attr %}class="w3-theme w3-animate-opacity"{% endblock %}

{% block content_display %}w3-display-middle{% endblock %}

{% block content %}
<h1 class="w3-border-bottom w3-margin">{{ memo.memo_title }}</h1>
<div class="w3-border-bottom w3-margin">
    <textarea class="w3-input w3-text-theme w3-theme-light w3-border" rows="7" disabled>
        {{ memo.memo_text }}
    </textarea>
</div>

<div class="w3-bar">
    <form class="w3-bar-item w3-mobile" action="{% url 'wemo_app:memo_delete' memo.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="w3-button w3-border w3-round-large w3-ripple">
            <i class="material-icons w3-small">delete メモを削除する</i>
        </button>
    </form>
    <div class="w3-bar-item w3-mobile">
        <a href="{% url 'wemo_app:memo_list' %}" class="w3-button w3-border w3-round-large w3-ripple">
            <i class="material-icons w3-small">home メモ一覧に戻る</i>
        </a>
    </div>
    <div class="w3-bar-item w3-mobile">
        <a href="{% url 'wemo_app:memo_update' memo.id %}" class="w3-button w3-border w3-round-large w3-ripple">
            <i class="material-icons w3-small">edit メモを書き直す</i>
        </a>
    </div>
</div>
{% endblock %}